### ISSUE TITLE
`UID FETCH` parsing issue?

### ISSUE THREAD

**Issue by sanmai-NL** [djc/tokio-imap#11]
While processing many e-mails, this error is thrown. The unwrap is in my code I think. The backtrace isn’t complete, perhaps because I use `futures-cpupool`. I’m debugging the issue right now.

```
uid: 11895
source length: 14634

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UidFetch { cause: Custom { kind: Other, error: StringError("bytes remaining on stream") } }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::result::unwrap_failed
  10: basic::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  15: main
  16: __libc_start_main
  17: _start
```

**Comment by djc** [comment]
Looks like it's coming from https://github.com/tokio-rs/tokio-io/blob/d0ea1a2bd7dcb2f284612e64dde9c4e0b7d1bc22/src/framed_read.rs#L86, meaning there might some edge-case at end of stream? Could your socket be unexpectedly closed?

**Comment by djc** [comment]
If this is reproducible, it would be great if you can capture the buffer contents when this happens. The best way to do this might be to override the `decode_eof()` implementation for `Decoder` of `ImapCodec` to print the byte contents of the `buf` argument before it does anything else.

**Comment by jonhoo** [comment]
I wonder if this is the same thing I'm seeing. Specifically, if I try to parse the (incomplete) line:
```
* 4 FETCH (UID 71372 RFC822.HEADER {10275}\r\n
```
I get:
```
IResult::Error(Position(Alt, [42, 32, 52, 32, 70, 69, 84, 67, 72, 32, 40, 85, 73, 68, 32, 55, 49, 51, 55, 50, 32, 82, 70, 67, 56, 50, 50, 46, 72, 69, 65, 68, 69, 82, 32, 123, 49, 48, 50, 55, 53, 125, 13, 10]))
```
instead of an `IResult::Incomplete`, which is what I was expecting?

**Comment by djc** [comment]
@jonhoo that is just due to missing support for `RFC822.HEADER`, which e25a5c8 now implements. Thanks for the good test case!

**Comment by jonhoo** [comment]
Ahh :heart:
